#!/bin/bash

echo "🚀 CLEAN STAFF AVAILABILITY FIX - NO COLUMN ERRORS"
echo "=================================================="
echo ""
echo "⚠️  This version removes ALL problematic table references"
echo "    and focuses ONLY on adding staff scheduling to the database."
echo ""
echo "💡 What this SQL does:"
echo "   ✅ Adds work_schedule column to shop_staff table"
echo "   ✅ Adds leave_dates column to shop_staff table" 
echo "   ✅ Updates shop_complete view to include these fields"
echo "   ✅ Initializes existing staff with Mon-Fri 9-5 schedule"
echo "   ✅ NO problematic discount/special tables referenced"
echo ""
echo "=================================================="
echo "📄 COPY THIS CLEAN SQL (NO COLUMN ERRORS):"
echo "=================================================="
cat staff-availability-fix-clean.sql
echo ""
echo "=================================================="
echo ""
echo "🎯 AFTER RUNNING THIS SQL:"
echo "   1. Your staff will have work_schedule and leave_dates in database"
echo "   2. Refresh your React Native app"
echo "   3. Go to provider booking and select 'Test test' staff member"
echo "   4. Calendar should show weekends as gray (not working)"
echo "   5. Weekdays should show as green (available)"
echo "   6. Console logs will show staff data with scheduling fields"
echo ""
echo "🔍 If you still see all green dots after running SQL + refreshing:"
echo "   - Check browser console for staff data logs"
echo "   - Make sure you selected a specific staff member (not 'Any available staff')"
echo "   - Verify the SQL completed without errors"